#include "Items.h"

const std::array<Area, NUM_AREAS> AREAS = {
	// =========================== Main areas =========================== 
	Area{
		"Spring Meadows",
		{Lanceram, Lighterim},
		{Dodger, CriticalBurn, BurningShots, DeadEnergyII, AugmentedAttack, AegisRevival, EmpoweringAttack, CleansingTint},
		{OutfitGustave_Baguette, HaircutGustave_Baguette},
		{Journal81},
	},
	Area{
		"Flying Waters",
		{Brulerum, Cruleram, Troubadim, Deminerim},
		{SOSShell, MarkingShots, RewardingMark, AugmentedCounterI, EnergisingBreak, ExposingAttack, AugmentedAim, StaggeringAttack, Versatile},
		{HaircutMaelle_Short},
		{Journal68},
	},
	Area{
		"Ancient Sanctuary",
		{Sakaram, Trebuchim},
		{EnergisingStartII, AttackLifesteal, EnergisingJump, Breaker, PiercingShot, BurningMark, StunBoost},
		{OutfitLune_Baguette, HaircutLune_Baguette},
		{Journal63},
	},
	Area{
		"Gestral Village",
		{Trebuchim, Betelim, Medalum, Sidaro, Hevasson, Demonam, Sekarum},
		{Roulette, PowerfulShots, CriticalMoment, HealingMark, AugmentedAim},
		{OutfitMaelle_Sakapatate, OutfitLune_Sakapatate, OutfitGustave_Sakapatate, OutfitSciel_Sakapatate, OutfitGustave_Pure, HaircutGustave_Gestral},
		{Journal52},
	},
	Area{
		"Esquie's Nest",
		{},
		{AugmentedFirstStrike, EnergisingStartIII},
		{OutfitSciel_Baguette, HaircutSciel_Baguette},
		{Journal66},
	},
	Area{
		"Stone Wave Cliffs",
		{Delaram, Duenum, Coralim},
		{BreakingCounter, FirstStrike, SOSPower, BreakingShots, AutoShell, HealingTintEnergy, AtDeathsDoor, Tainted, EnfeeblingMark, DefensiveMode, RejuvenatingRevive, Confident, EnergisingPain, PerilousParry},
		{OutfitMaelle_Skirt},
		{Journal50, Journal56, Journal78},
	},
	Area{
		"Forgotten Battlefield",
		{Troubadim, Lusteson, Dualiso, Benisim},
		{LongerShell, EnergisingStartIV, EnergisingDeath, EnergisingParry, EmpoweringTint, ComboAttackI, ReviveTintEnergy, SweetKill, InvertedAffinity},
		{OutfitMaelle_Obscur},
		{Journal41, Journal57},
	},
	Area{
		"Monoco's Station",
		{},
		{},
		{},
		{Journal65},
	},
	Area{
		"Old Lumiere",
		{Nusaro, Melarum, Algueron, Battlum, Redalim},
		{HealingCounter, LongerPowerful, AutoRush, HealingDeath, TimeTint, PerilousParry},
		{},
		{JournalSurvivor, Journal42, Journal58, JournalRenoir},
	},
	Area{
		"Visages",
		{Clierum, Confuso, Chapelim, Sadon},
		{PoweredAttack, DoubleBurn, ConfidentFighter, AugmentedCounterII, GlassCannon, Immaculate, HealingShare},
		{},
		{Journal39, Journal69, JournalUnknown1},
	},
	Area{
		"Sirene",
		{Tissenum, Tisseron, BarrierBreaker, Chantenum},
		{ShieldAffinity, EffectiveHeal, GreaterShell, AutoRegen, ProtectingDeath, AntiCharm, DoubleMark, EnergisingAttackII, GreaterPowerful, HealingFire, PowerfulOnShell},
		{HaircutLune_Sirene, OutfitLune_Sirene},
		{Journal55, Journal67},
	},
	Area{
		"The Monolith",
		{Braselim, Dreameso, Lithelim, Fragaro, Veremum},
		{StayMarked, WeaknessGain, EnfeeblingAttack, BreakingAttack, EmpoweringParry, ComboAttackII, EnergisingCleanse, RandomDefense, GreaterDefenceless},
		{HaircutMaelle_Voluminous},
		{Journal70, JournalAline},
	},
	Area{
		"The Manor",
		{},
		{},
		{OutfitMaelle_Skirt, OutfitVerso_Civilian, OutfitMaelle_PaintedMe, HaircutMaelle_Rebellious},
		{JournalAline, JournalRenoir, JournalUnknown3},
	},
	Area{
		"Lumiere (Act III)",
		{Liteso, Litheson, Potierim, Volesterum, Ballaro, Gaulteram, Sadon},
		{Shortcut, EnergisingPowerful, ChargingStun, AugmentedCounterIII, HealingStun, GradientFighter, FasterThanStrong, FullStrength},
		{},
		{Journal60},
	},
	// =========================== Side areas =========================== 
	Area{
		"Abbest Cave",
		{},
		{FirstOffensive},
		{},
		{},
	},
	// Area{
	// 	"Ancient Gestral City",
	// 	{},
	// 	{},
	// 	{},
	// 	{},
	// },
	// Area{
	// 	"Blades' Graveyard",
	// 	{},
	// 	{},
	// 	{},
	// 	{},
	// },
	// Area{
	// 	"Boat Graveyard",
	// 	{},
	// 	{},
	// 	{},
	// 	{},
	// },
	Area{
		"Coastal Cave",
		{Lanceram, Lighterim, Seeram, Brulerum, Cruleram, Deminerim, Gobluson, Bourgelon},
		{},
		{},
		{},
	},
	Area{
		"Crimson Forest",
		{Chevalam},
		{},
		{},
		{},
	},
	Area{
		"Crushing Cavern",
		{},
		{Solidifying},
		{},
		{Journal45},
	},
	Area{
		"Dark Gestral Arena",
		{Trebuchim, Sakaram},
		{ComboAttackIII},
		{HaircutMaelle_GestralWhite},
		{},
	},
	Area{
		"Dark Shores",
		{Corpeso},
		{InMediasRes},
		{},
		{},
	},
	Area{
		"Endless Night Sanctuary",
		{Joyaro, Cruleram},
		{QuickBreak, GradientBreak},
		{},
		{},
	},
	Area{
		"Endless Tower",
		{Duollison, Cleim},
		{TimeTint, FuelingBreak, EnergisingRush, ChargingCritical, EmpoweringTint, CriticalWeakness, GreaterPowerless, RushOnPowerful, GreaterDefenceless, FirstLife, CleasDeath},
		{OutfitVerso_Clair, HaircutSciel_Clea, HaircutLune_Clea, HaircutMaelle_PonytailWhite, HaircutLune_RebelliousWhite, HaircutVerso_ExpeditionWhite, HaircutSciel_MessyBunWhite, HaircutMaelle_DoubleBraidWhite, HaircutLune_Simon, HaircutMaelle_Simon, HaircutVerso_Simon, HaircutMonoco_Simon, HaircutSciel_Simon, OutfitVerso_Visages},
		{},
	},
	Area{
		"Esoteric Ruins",
		{},
		{ProtectingHeal},
		{},
		{},
	},
	Area{
		"Falling Leaves",
		{Glaisum, Scaverim, Direton},
		{SOSRush, BeneficialContamination},
		{},
		{Journal35, Journal49},
	},
	Area{
		"Floating Cemetary",
		{},
		{AutoPowerful},
		{},
		{},
	},
	Area{
		"Flying Casino",
		{},
		{},
		{OutfitMonoco_Lumiere},
		{},
	},
	Area{
		"Flying Manor",
		{Ramasson, Snowim, Joyaro, Battlum, Abysseram, Chation, Cruleram, Saperim, Lighterim, Dualiso, Lanceram, Troubadim, Glaceso, Martenon, Sidaro, Seashelum, Elerim, Gesam},
		{AcceleratingShots, AntiBurn, AugmentedCounterI, BreakSpecialist, BurningDeath, ChargingAlteration, CleasLife, EmpoweringBreak, EmpoweringParry, EnergeticHealer, EnergisingPain, EnergisingShots, EnergisingStun, GradientBreaker, LongerBurn, LongerShell, Painter, PowerfulMark, PowerfulRevive, ProtectingShots, Roulette, SlowingBreak, StayMarked},
		{HaircutMaelle_Clea},
		{},
	},
	Area{
		"Frozen Hearts",
		{Stalum, Snowim},
		{BurningBreak, BurnAffinity, EnergisingBurn, AntiFreeze, AntiBurn},
		{OutfitLune_Danseuse, OutfitVerso_Pelerin, OutfitSciel_Danseuse, HaircutLune_Short},
		{Journal51},
	},
	Area{
		"Gestral Beach (All)",
		{},
		{},
		{OutfitLune_Swimsuit1, OutfitLune_Swimsuit2, OutfitVerso_Swimsuit1, OutfitMaelle_Swimsuit, OutfitSciel_Swimsuit2, OutfitGustave_Swimsuit, OutfitMonoco_Swimsuit},
		{Journal37},
	},
	Area{
		"Hidden Gestral Arena",
		{},
		{LastStandCritical, AcceleratingLastStand, ProtectingLastStand, SoloFighter, EmpoweringLastStand},
		{},
		{},
	},
	Area{
		"Isle of the Eyes",
		{Facesum},
		{},
		{},
		{},
	},
	// Area{
	// 	"Lost Woods",
	// 	{},
	// 	{},
	// 	{},
	// 	{},
	// },
	Area{
		"Painting Workshop",
		{},
		{AtDeathsDoor, EnergisingAttackI},
		{},
		{},
	},
	Area{
		"Red Woods",
		{},
		{Recovery},
		{},
		{},
	},
	Area{
		"Renoir's Drafts",
		{},
		{RushOnPowerful, SecondChance},
		{},
		{},
	},
	Area{
		"Sacred River",
		{},
		{EnergisingParry, Solidifying, DoubleBurn, RewardingMark, StunBoost, ShieldAffinity, GlassCannon, EmpoweringAttack, ReviveTintEnergy, BurningShots, CriticalStun, EnergisingTurn},
		{},
		{},
	},
	Area{
		"Sinister Cave",
		{Elerim, Chalium, Corderon},
		{},
		{},
		{},
	},
	Area{
		"Sirene's Dress",
		{Choralim, Ballaro},
		{},
		{},
		{Journal46},
	},
	Area{
		"Sky Island",
		{Urnaro},
		{GreaterSlow},
		{},
		{},
	},
	Area{
		"Stone Quarry",
		{},
		{HealingParry},
		{},
		{Journal48},
	},
	Area{
		"Stone Wave Cliffs Cave",
		{},
		{EnergisingRevive, ExhaustingPower},
		{},
		{Journal54},
	},
	Area{
		"Sunless Cliffs",
		{},
		{TheOne},
		{HaircutMaelle_Bald, HaircutVerso_Bald, HaircutLune_Bald, HaircutSciel_Bald, HaircutMonoco_Bald},
		{},
	},
	Area{
		"The Abyss",
		{Simoso},
		{},
		{},
		{JournalSimon},
	},
	// Area{
	// 	"The Canvas",
	// 	{},
	// 	{},
	// 	{},
	// 	{},
	// },
	Area{
		"The Carousel",
		{},
		{},
		{HaircutMaelle_FrenchBob},
		{},
	},
	Area{
		"The Chosen Path",
		{Contorso},
		{BaseShield},
		{},
		{},
	},
	Area{
		"The Crows",
		{Minason},
		{ShieldingDeath},
		{},
		{Journal34},
	},
	Area{
		"The Fountain",
		{},
		{},
		{},
		{Journal84},
	},
	// Area{
	// 	"The Meadows",
	// 	{},
	// 	{},
	// 	{},
	// 	{},
	// },
	Area{
		"The Reacher",
		{Tireso, Lithum},
		{DrainingCleanse, Sniper, LongerShell, ChargingCounter, ChargingAttack, ProtectingTint, AntiBlight, ExposingBreak, ChargingWeakness, Tainted, ProtectingHeal, HealingBoon},
		{OutfitMaelle_Baguette, HaircutMaelle_Baguette, HaircutMaelle_PaintedMe},
		{JournalUnknown2, Journal61},
	},
	Area{
		"The Small Bourgeon",
		{},
		{},
		{},
		{Journal53},
	},
	// Area{
	// 	"Twilight Quarry",
	// 	{},
	// 	{},
	// 	{},
	// 	{},
	// },
	Area{
		"Verso's Drafts",
		{Baguettaro, Bonbim, Cannaro, Esqium, Esquiaro, Esquim, Esquion, Licorum, Sucetton, Sucreso},
		{AlternatingCritical, APDiscount, ConsumingAttack, DamageShare, DoubleThird, EmpoweredHealer, EmpoweringJumps, Feint, Frenzy, GradientOvercharge, GradientParry, LongerBreak, SlowingAttack, SOSHealingTint, TriggerHappy},
		{HaircutMonoco_Baguette, OutfitMonoco_Baguette, HaircutMaelle_Chic, HaircutVerso_Chic, HaircutLune_DoubleBun, HaircutMaelle_DoubleBun, HaircutMonoco_DoubleBun, HaircutSciel_DoubleBun, HaircutLune_Esquie, HaircutMaelle_Esquie, HaircutVerso_Esquie, HaircutSciel_Esquie, HaircutMonoco_Esquie, OutfitLune_Esquie, OutfitMaelle_Esquie, OutfitVerso_Esquie, OutfitSciel_Esquie, OutfitMonoco_Esquie, HaircutMaelle_FrenchBob},
		{},
	},
	// Area{
	// 	"White Sands",
	// 	{},
	// 	{},
	// 	{},
	// 	{},
	// },
	Area{
		"White Tree",
		{},
		{},
		{},
		{Journal36},
	},
	Area{
		"Yellow Harvest",
		{Gaulteram, Potierim, Plenum, Kralim},
		{DeathBomb, AutoDeath, Teamwork, EnergisingAttackI},
		{HaircutLune_Wavy, HaircutMaelle_Braid},
		{Journal38, Journal44, Journal59},
	},
};
